
name: hello from main

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    if: startsWith(github.event.ref, 'ma')
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
