---
name: Context testing
on:
  release:
    types: [published] 
  push:
  delete:
  pull_request:
    types: [ opened, closed, reopened, synchronize ]
    branches:
      - "main"
  workflow_dispatch:
    inputs:
      some_tag:
        description: IDKLOL
        required: true
        type: string

jobs:

  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      - name: Dump job context
        run: echo '${{ toJSON(job) }}'
      - name: Dump steps context
        run: echo '${{ toJSON(steps) }}'
      - name: Dump runner context
        run: echo '${{ toJSON(runner) }}'
      - name: Dump strategy context
        run: echo '${{ toJSON(strategy) }}'
      - name: Dump matrix context
        run: echo '${{ toJSON(matrix) }}'
      - name: Dump inputs context
        run: echo '${{ toJSON(inputs) }}' || true
