name: Release Workflow

on:
  release:
    types: [published]
    branches:
      - feature/*

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add your deployment steps here
      - name: Deploy
        run: |
          echo 'run. do not walk'