name: Update QA Ephemeral Env

on:
  push:
    branches:
      - 'qa/**'

jobs:
  create-environment:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"