
# ---

# name: Q group tester

# concurrency:
#   group: feature-${{ github.event_name == 'delete' && format('refs/heads/{0}', github.event.ref) || github.event.ref }}
#   cancel-in-progress: false

# on:
#   delete:
#   push:


# jobs:

#   dump_contexts_to_log:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Dump GitHub context
#         id: github_context_step
#         run: echo '${{ toJSON(github) }}'
#       - name: shleep
#         run: sleep 60
