---

name: hello service containers

on:
  push:

env:
  environment: integration

jobs:
  test:
    name: Test
    runs-on: "ubuntu-latest"

    services:

      redis:
        image: redis:6.2
        ports:
          - 6379:6379

      mysql:
        image: mysql:8
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: 1
        ports:
          - 3306:3306
    
    steps:

      - run: |
        docker network ls

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
