---

name: slack webhooks

on:
  push:

env:
  env_value: greattor

jobs:

  hellur:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:

      - uses: act10ns/slack@v1.6.0
        with:
          status: Starting....!
          config: .github/config/slack.yaml

      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
          SLACK_ICON: https://confidence.corsis.com/favicon-32x32.png
          SLACK_MESSAGE: 'Post Content :eggplant: :eggplant: :eggplant:'
          SLACK_TITLE: Post Title
          SLACK_USERNAME: ConfiBot
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}

      - uses: 8398a7/action-slack@v3
        with:
          icon_url: https://confidence.corsis.com/favicon-32x32.png
          icon_emoji: ":eggplant:"
          username: mrYouZorg
          author_name: mrBoopyBorthole
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took,pullRequest # selectable (default: repo,message)
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required

  failur:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - run: exit 1

  succos:
    runs-on: ubuntu-latest
    steps:
      - run: exit 0

  slacker:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:

      - name: Summarize Workflow Status Action
        id: workflow-status
        uses: takayamaki/summarize-workflow-status@v1.0.0

      - uses: act10ns/slack@v1.6.0
        with:
          status: ${{ steps.workflow-status.outputs.status }}
          message: try https://butt.holdings/