---

name: slack webhooks

on:
  push:

jobs:
  slacker:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:

      - uses: act10ns/slack@v1.5
        with:
          status: starting
          config: .github/config/slack.yaml

      - uses: act10ns/slack@v1.5
        with:
          status: ${{ job.status }}