---

name: slack webhooks

on:
  push:

env:
  env_value: greattor

jobs:

  hellur:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:

      - uses: act10ns/slack@v1.5.0
        with:
          status: Starting....!
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
          SLACK_ICON: https://confidence.corsis.com/favicon-32x32.png
          SLACK_MESSAGE: 'Post Content :eggplant: :eggplant: :eggplant:'
          SLACK_TITLE: Post Title
          SLACK_USERNAME: ConfiBot
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}

  failur:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - run: exit 1

  succos:
    runs-on: ubuntu-latest
    steps:
      - run: exit 0

  slacker:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:

      # - id: github-script
      #   uses: actions/github-script@v6
      #   with:
      #     github-token: ${{ github.token }}
      #     script: |
      #       const wfRunJobs = await github.rest.actions.listJobsForWorkflowRun({
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         run_id: context.runId
      #       })

      - name: Summarize Workflow Status Action
        id: workflow-status
        uses: takayamaki/summarize-workflow-status@v1.0.0

      - uses: act10ns/slack@v1.5.0
        with:
          status: ${{ steps.workflow-status.outputs.status }}